### PR TITLE
Replaces a few plain text words in mustache file

### PR DESCRIPTION
**Pull request by ameliav**
Replaces a few plain text words in mustache file

## 🗣 Description ##

Replacement made at report.mustache line 314 from “(email links clicked divided by emails sent)” to “and report rates”. PCDEV-107 request from Kelly Thiele.

## 💭 Motivation and context ##

Not a code change. This will update the mustache file's text with a couple new words.

## 🧪 Testing ##

N/A

## 📷 Screenshots (if appropriate) ##

N/A

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.

### CODE REVIEW

**Review by BenBreaksThings — APPROVED** [review]
Exactly what was needed, does not alter code base, just reporting output.

**Comment by jsf9k** [comment]
@ameliav and @BenBreaksThings, why did you merge this if the tests didn't pass?  There should be branch protections in place anyway to prevent this.

**Comment by dav3r** [comment]
We can enable those branch protections once #3 has been cleaned up and merged- that should be made a priority before any further development is done in this repo.

@ameliav and @BenBreaksThings - I realize now that we should do something slightly different than what I mentioned to you in chat...  After #3 is merged, someone on @cisagov/cyhy-pca should be tasked with the following:

1. Migrate this repo from being a descendant of [`skeleton-generic`](https://github.com/cisagov/skeleton-generic) to [`skeleton-python-library`](https://github.com/cisagov/skeleton-python-library).  
2. Create a new repo called `pca-report-generator-docker` (based on [`skeleton-docker`](https://github.com/cisagov/skeleton-docker)) and rip the Docker bits out of this repo and put them in `pca-report-generator-docker`.

The payoff at the end of this will be cleaner, more maintainable and testable code, separation of Python and Docker code, and automated deployment of [Docker images to DockerHub](https://hub.docker.com/r/cisagov/pca-report-generator).

CC: @teal-e, @felddy, @jsf9k, @mcdonnnj

**Comment by mcdonnnj** [comment]
> 
> 
> We can enable those branch protections once #3 has been cleaned up and merged- that should be made a priority before any further development is done in this repo.
> 
> @ameliav and @BenBreaksThings - I realize now that we should do something slightly different than what I mentioned to you in chat... After #3 is merged, someone on @cisagov/cyhy-pca should be tasked with the following:
> 
>     1. Migrate this repo from being a descendant of [`skeleton-generic`](https://github.com/cisagov/skeleton-generic) to [`skeleton-python-library`](https://github.com/cisagov/skeleton-python-library).
> 
>     2. Create a new repo called `pca-report-generator-docker` (based on [`skeleton-docker`](https://github.com/cisagov/skeleton-docker)) and rip the Docker bits out of this repo and put them in `pca-report-generator-docker`.
> 
> 
> The payoff at the end of this will be cleaner, more maintainable and testable code, separation of Python and Docker code, and automated deployment of [Docker images to DockerHub](https://hub.docker.com/r/cisagov/pca-report-generator).
> 
> CC: @teal-e, @felddy, @jsf9k, @mcdonnnj

I think this is the right path. I would suggest flipping the order though. I think it will be more straightforward to do a PR to rip out the Docker parts at the same time as a new repo is made, and then once this is just Python code switch to descending from [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library).

**Comment by dav3r** [comment]
> I think this is the right path. I would suggest flipping the order though. I think it will be more straightforward to do a PR to rip out the Docker parts at the same time as a new repo is made, and then once this is just Python code switch to descending from [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library).

That is an excellent suggestion @mcdonnnj - I agree wholeheartedly.  👍 

So the updated plan should be:

1. Get this repo up-to-date with [`skeleton-generic`](https://github.com/cisagov/skeleton-generic) by following the instructions in #3 and getting that PR merged.
2. Create a new repo called `pca-report-generator-docker` (based on [`skeleton-docker`](https://github.com/cisagov/skeleton-docker)).
3. Rip the Docker bits out of this repo and put them in `pca-report-generator-docker`. 
4. Migrate this repo from being a descendant of [`skeleton-generic`](https://github.com/cisagov/skeleton-generic) to [`skeleton-python-library`](https://github.com/cisagov/skeleton-python-library).

Please reach out to your friendly-neighborhood Dev team members if you have any questions or run into any issues while doing the tasks above.

**Pull request merged**
