### PR TITLE
Replaces a few plain text words in mustache file 

### PR DESCRIPTION
**Pull request by ameliav**
#  #
Replaces a few plain text words in mustache file

## 🗣 Description ##

Change narrative references of "key finding recommendations" to "key findings and recommendations". PCADEV-168 request from Kelly Thiele.

## 💭 Motivation and context ##

Not a code change. This will update the mustache file's text with a couple new words.

## 🧪 Testing ##

N/A

## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.

### CODE REVIEW

**Comment by dav3r** [comment]
This PR appears to include many code changes, despite the PR title and description that say otherwise.  What's the deal here?

**Comment by ameliav** [comment]
@dav3r I made this branch off of the skeletonize branch because the report.mustache file location gets changed in skeletonize branch. If I used the develop branch for new changes before the folder structure changes in skeletonize, will it be able to be pulled into PR#9?

**Comment by dav3r** [comment]
> @dav3r I made this branch off of the skeletonize branch because the report.mustache file location gets changed in skeletonize branch. If I used the develop branch for new changes before the folder structure changes in skeletonize, will it be able to be pulled into PR#9?

You should just make the changes for this PR based off of the `develop` branch.  If #9 gets merged before this one does, you will have to merge those changes into this PR, but that should be simple.  As it stands right now, this PR includes all of the changes from the not-yet-approved `skeletonize` branch, which is not what we should be focusing on here.

**Comment by ameliav** [comment]
Okay, I will create a new branch off develop and make the changes in /src/customer/report.mustache and then it sounds like you're saying it is simple to move it to /src/pca-report-library/asssets/report.mustache in skeletonize. This was what I was not sure about.
I will close this PR once the other one is set up.
@dav3r New one is here https://github.com/cisagov/pca-report-library/pull/15

**Pull request closed without merging**
